  <ItemGroup Condition="'$(Language)' == 'C#' AND ('$(ImplicitUsings)' == 'true' or '$(ImplicitUsings)' == 'enable')">
    <Using Include="Cake.Frosting" />
    <Using Include="Cake.Core" />
    <Using Include="Cake.Core.Diagnostics" />
    <Using Include="Cake.Core.IO" />
    <Using Include="Cake.Common" />
    <Using Include="Cake.Common.Build" />
    <Using Include="Cake.Common.Diagnostics" />
    <Using Include="Cake.Common.IO" />
    <Using Include="Cake.Common.Net" />
    <Using Include="Cake.Common.Security" />
    <Using Include="Cake.Common.Solution" />
    <Using Include="Cake.Common.Solution.Project" />
    <Using Include="Cake.Common.Solution.Project.Properties" />
    <Using Include="Cake.Common.Solution.Project.XmlDoc" />
    <Using Include="Cake.Common.Text" />
    <Using Include="Cake.Common.Tools.Cake" />
    <Using Include="Cake.Common.Tools.Chocolatey" />
    <Using Include="Cake.Common.Tools.Command" />
    <Using Include="Cake.Common.Tools.DotCover" />
    <Using Include="Cake.Common.Tools.DotNet" />
    <Using Include="Cake.Common.Tools.DupFinder" />
    <Using Include="Cake.Common.Tools.Fixie" />
    <Using Include="Cake.Common.Tools.GitLink" />
    <Using Include="Cake.Common.Tools.GitReleaseManager" />
    <Using Include="Cake.Common.Tools.GitVersion" />
    <Using Include="Cake.Common.Tools.ILMerge" />
    <Using Include="Cake.Common.Tools.ILRepack" />
    <Using Include="Cake.Common.Tools.InnoSetup" />
    <Using Include="Cake.Common.Tools.InspectCode" />
    <Using Include="Cake.Common.Tools.MsBuild" />
    <Using Include="Cake.Common.Tools.MSpec" />
    <Using Include="Cake.Common.Tools.MSTest" />
    <Using Include="Cake.Common.Tools.NSIS" />
    <Using Include="Cake.Common.Tools.NuGet" />
    <Using Include="Cake.Common.Tools.NUnit" />
    <Using Include="Cake.Common.Tools.OctopusDeploy" />
    <Using Include="Cake.Common.Tools.OpenCover" />
    <Using Include="Cake.Common.Tools.ReportGenerator" />
    <Using Include="Cake.Common.Tools.ReportUnit" />
    <Using Include="Cake.Common.Tools.Roundhouse" />
    <Using Include="Cake.Common.Tools.SignTool" />
    <Using Include="Cake.Common.Tools.SpecFlow" />
    <Using Include="Cake.Common.Tools.TextTransform" />
    <Using Include="Cake.Common.Tools.VSTest" />
    <Using Include="Cake.Common.Tools.VSWhere" />
    <Using Include="Cake.Common.Tools.WiX" />
    <Using Include="Cake.Common.Tools.XBuild" />
    <Using Include="Cake.Common.Tools.XUnit" />
    <Using Include="Cake.Common.Xml" />
  </ItemGroup>
